### ISSUE TITLE
Problem with Model_D1

### ISSUE THREAD

**Issue by smhr** [djurin/GALIC#1]
Hi @djurin 

When I run the code with:
```
mpirun -np 1 GalIC ./Model_D1.param
```
I get this error:
```
Code termination on task=0, function mymalloc_movable_fullinfo(), file src/mymalloc.c, line 336: 
Task=0: Not enough memory in mymalloc_fullinfo() to allocate 19940.4 MB for variable 'P' at allocate_memory()/src/allocate.c/line 53 (FreeBytes=2274.12 MB).
```
The `free -h` says:
```
             total       used       free     shared    buffers     cached
Mem:           62G       3.1G        59G       5.8M        24K       382M
-/+ buffers/cache:       2.7G        60G
Swap:         2.0G        52M       2.0G
```

**Comment by denisyurin** [comment]
Hi @smhr 

Please, try to increase MaxMemSize in the parameter file or the number of tasks with which you run the code.

**Comment by smhr** [comment]
Many thanks. I do that, but I found that the main reason would be the 100000000 value in construction of density and force field, because without reducing it (to 10000000 for example) the problem was not solved.

**Comment by denisyurin** [comment]
Sure you can do this, but it comes with a cost of quality degradation of the target density and lookup acceleration fields, they get more noisy.

**Comment by smhr** [comment]
Thanks again.

**Comment by FisAleBugarin** [comment]
which the MaxMemSize for M1 model?
